### ISSUE TITLE
Azure DevOps issues with YAML templates referenced by tag

### ISSUE THREAD

**Issue by Plesoo** [github/gh-actions-importer#219] opened 2023-07-26 10:48 UTC
Hello,

I'm running gh actions importer on Ubuntu, here are the versions:
- gh version 2.32.1 (2023-07-24)
- gh actions-importer     github/gh-actions-importer      v1.3.3
- actions-importer/cli:latest     v1.3.20193

and it seems that the tool is having some issues with Azure DevOps YAML templates referenced using tags.

### Azure Pipelines YAML setup
In my pipeline I'm referencing YAML template from another repo using tag reference in this way:
```
resources:
  repositories:
    - repository: repo
      type: git
      name: projectName/repoName
      ref: refs/tags/1.5.0
```
### Issue
After running `gh actions-importer audit azure-devops --output-dir tmp/audit` command for repos that are using tag reference to YAML templates in results I'm getting error.txt with such content:
```
There was an error extracting the Azure DevOps pipeline (https://dev.azure.com/organization/project/_build?definitionId=xxx)
Message: Resource not found
(GET 404) Not Found: https://dev.azure.com/organization/someOtherProject/_apis/git/repositories/repoName/items?api-version=5.0-preview&path=jobs%2FjobFileName.yml&versionDescriptor.version=1.5.0
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/parse_response.rb:16:in `parse!'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/adapters/azure_devops/client.rb:92:in `fetch_file'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/extract_file.rb:16:in `call'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/adapters/provider_resolver.rb:26:in `call'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/extract_file.rb:11:in `call'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:313:in `block (3 levels) in extract_included_files'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:288:in `map'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:288:in `block (2 levels) in extract_included_files'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:284:in `map'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:284:in `block in extract_included_files'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:283:in `each'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:283:in `flat_map'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:283:in `extract_included_files'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:84:in `deep_fetch_templates'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_templates.rb:59:in `call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_pipeline.rb:125:in `pipeline_attributes_from_client'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/pipeline/extract_pipeline.rb:53:in `extract'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/services/azure_devops/extract_all_pipelines.rb:38:in `block (2 levels) in build_pipelines'
/usr/local/bundle/gems/actions_importer-1.3.20193/lib/valet/models/thread_collection.rb:8:in `block in perform_later'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

Looks like URL query is missing additional parameter `versionDescriptor.versionType=tag` because when I add that manually to the URL I'm able to download the file in browser properly.

I would like to ask whether I'm doing something wrong or this is actually a bug in the importer tool?

**Comment by ethanis** [comment] 2023-07-26 22:01
@Plesoo sorry to see that you are running into this error! This does look like a bug, however, can you please open a [support ticket](https://github.com/github/gh-actions-importer#how-to-request-support) so that we can properly triage this and get you help?

**Comment by Plesoo** [comment] 2023-07-27 08:24
@ethanis thanks for response, however I'm not able to create a ticket following your link. Once I'm at https://support.github.com/request/actions I see no matching category for reporting such issues and also some of them like "Provide feedback" doesn't allow me to create a ticket but to create a discussion which is probably not that you suggested to do. Could you please clarify how to properly create a ticket for such matter?

**Comment by simonsanchez** [comment] 2023-07-27 23:26
@Plesoo opening an issue here works. I was able to reproduce your issue and this will be fixed in an upcoming release.

**Comment by Plesoo** [comment] 2023-07-28 07:29
@simonsanchez that's great :) any estimates when that fix could be released?

**Comment by simonsanchez** [comment] 2023-07-28 16:49
The fix is live. Please update the tool to the latest version using `gh actions-importer update`.

**Comment by Plesoo** [comment] 2023-07-31 09:00
I have updated the tool and ran it and it looks like error from first post is gone, however now I'm getting another one but this time it's not possible for me to figure out what is the reason. Here is content of error.txt
```
There was an internal error transforming the Azure DevOps pipeline (projectName/repoName) into a GitHub Actions workflow.
Please reference 'f8e4874c8e1060cc3329f7a23c7d7315debc6761' when requesting support.
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:286:in `report_error'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation_2_7.rb:787:in `block in create_validator_method_medium3'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:107:in `block (2 levels) in needed_jobs'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:106:in `map'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:106:in `block in needed_jobs'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:102:in `each'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:102:in `needed_jobs'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation_2_7.rb:837:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation_2_7.rb:837:in `block in create_validator_method_medium3'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:54:in `block (2 levels) in initialize'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:53:in `each'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:53:in `block in initialize'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:31:in `each'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/pipeline/job_graph_builder.rb:31:in `initialize'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:45:in `new'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:45:in `build_jobs'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:115:in `transform_template'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:55:in `block in build_jobs'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:49:in `each'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:49:in `build_jobs'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/transformers/azure_devops/pipeline/jobs.rb:34:in `transform'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `bind_call'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
/usr/local/bundle/gems/sorbet-runtime-0.5.10648/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/transform_pipeline.rb:122:in `jobs'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/services/azure_devops/transform_pipeline.rb:76:in `call'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/adapters/provider_resolver.rb:82:in `call'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/commands/audit.rb:33:in `block (2 levels) in call'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/commands/audit.rb:32:in `map'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/commands/audit.rb:32:in `block in call'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/logger.rb:92:in `with_progress_bar'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/commands/audit.rb:31:in `call'
/usr/local/bundle/gems/actions_importer-1.3.20305/lib/valet/subcommands/audit.rb:52:in `azure_devops'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/actions_importer-1.3.20305/exe/actions-importer:19:in `<top (required)>'
/usr/local/bundle/bin/actions-importer:25:in `load'
/usr/local/bundle/bin/actions-importer:25:in `<main>'
```

**Comment by simonsanchez** [comment] 2023-08-01 18:03
@Plesoo since the new error is different, please open a separate issue with the content above. If you are able to provide additional details and/or a reproducible sample, that would be immensely helpful. At this time I am not able to give you an exact date on when a fix will go out as the team will need time to dig into this.

**Closed by simonsanchez** 2023-08-01 18:03 UTC
