### ISSUE TITLE
Stack trace for the error...

### ISSUE THREAD

**Issue by Mzariez01** [github/gh-actions-importer#115] opened 2023-04-28 00:06 UTC
Stack trace for the error...
```
E, [2023-04-26T23:15:41.631853 #1] ERROR -- : undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:40:in `block in composite_actions'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:37:in `each'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:37:in `map'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:37:in `composite_actions'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/base/transform_pipeline/result/single.rb:61:in `composite_actions'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/base/transform_pipeline/result/single.rb:46:in `block in files'
<internal:kernel>:90:in `tap'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/base/transform_pipeline/result/single.rb:39:in `files'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/commands/audit.rb:42:in `block in call'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/commands/audit.rb:40:in `each'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/commands/audit.rb:40:in `call'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/subcommands/audit.rb:130:in `gitlab'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/actions_importer-1.2.18472/exe/actions-importer:19:in `<top (required)>'
/usr/local/bundle/bin/actions-importer:25:in `load'
/usr/local/bundle/bin/actions-importer:25:in `<main>'
```

_Originally posted by @bxscif in https://github.com/github/gh-actions-importer/issues/114#issuecomment-1524211184_

**Comment by j-dunham** [comment] 2023-04-28 00:48
Hi @Mzariez01 

GitHub Actions Importer does not support transforming a child pipeline that is dynamically created in a pipeline. The child pipeline needs to exist at transformation time so it can be added to the resulting Actions workflow. I have just merged a change so the rest of the pipeline should continue to be transform even though the child pipeline cannot be found. You can get this change by doing gh actions-importer update and then retrying.

**Comment by j-dunham** [comment] 2023-04-28 10:11
Closing duplicate of #114

**Closed by j-dunham** 2023-04-28 10:11 UTC
